config/routes.rb
Rails.application.routes.draw do
  get 'players/index'
  
  resources :players

  root 'players#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all
  end

  def show
  	@player = Player.find_by(id: params[:id])
  end

  def new
  	@player = Player.new
  end

  def create
  	@player = Player.new(player_params)

  	if @player.save
  		redirect_to root_path
  	end
  end
  
  def edit
  	@player = Player.find_by(id: params[:id])
  end

  def update
  	@player = Player.find_by(id: params[:id])

  	@player.update(player_params)
  	redirect_to root_path
  end

  def destroy
  	@player = Player.find_by(id: params[:id])
  	@player.destroy 
  	redirect_to root_path
  end

  private
  def player_params
  	params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url: player_path(@player.id) do |f| %>
  <%= f.text_field :nickname %><br>
  <%= f.text_field :rank %><br>
  <%= f.text_field :charisma %><br>
  <%= f.text_field :wisdom %><br>
  <%= f.submit "edit!" %>
<% end %>

app/views/players/index.html.erb
<h1>Add new player: </h1>
<%= link_to 'add', new_player_path %>
<h2>Listing of players</h2>
<% @players.each do |player| %>
       <p>
      <b><%= player.nickname %></b>
      <%= link_to 'show more...', player_path(player.id) %>
    </p>
  <% end %>

app/views/players/new.html.erb
<%= form_for @player, url: players_path do |f| %>
  <%= f.text_field :nickname %><br>
  <%= f.text_field :rank %><br>
  <%= f.text_field :charisma %><br>
  <%= f.text_field :wisdom %><br>
  <%= f.submit "add it!" %>
<% end %>

app/views/players/show.html.erb
      
      
       <p>
      <h2><b><%= @player.nickname %></b></h2><br>
      <p>has rank: </p><b><%= @player.rank %></b><br>
      <p>has charisma: </p><b><%= @player.charisma %></b><br>
      <p>has wisdom: </p><b><%= @player.wisdom %></b>
    </p>

    <%= link_to 'edit player', edit_player_path(@player.id) %><br>
    <%= link_to 'Destroy', player_path(@player.id),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
 